apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      run: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: 822642595439.dkr.ecr.ap-south-2.amazonaws.com/simple-angular-app:latest
        ports:
        - containerPort: 80

